# Generated by Django 4.2.2 on 2023-06-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazana_app', '0002_alter_user_detail_gender_alter_user_detail_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
    ]
