# Generated by Django 4.2.2 on 2023-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazana_app', '0003_alter_user_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Please select'), ('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', 'Please select'), ('company', 'Company'), ('user', 'User')], max_length=12, null=True),
        ),
    ]
