# Generated by Django 4.2.2 on 2023-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazana_app', '0004_alter_user_detail_gender_alter_user_detail_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='Please Select', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('user', 'User')], max_length=12, null=True),
        ),
    ]
